name: repo_sync_gitlab

on: 
  workflow_dispatch:
  push:
    branches: [ main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Mirror + trigger CI
      uses: SvanBoxel/gitlab-mirror-and-ci-action@master
      with:
        args: "https://jihulab.com/hbstarjason/jd-scripts-docker"
      env:
        GITLAB_HOSTNAME: "jihulab.com"
        GITLAB_USERNAME: "starjason"
        GITLAB_PASSWORD: ${{ secrets.JIHULAB }}
        GITLAB_PROJECT_ID: "25786"
        GITHUB_TOKEN: ${{ secrets.PAT }} 
