name: Mirror and run GitLab CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Mirror + trigger CI
      uses: SvanBoxel/gitlab-mirror-and-ci-action@master
      with:
        args: "https://jihulab.com/hbstarjason/jd-scripts-docker"
      env:
        GITLAB_HOSTNAME: "jihulab.com"
        GITLAB_USERNAME: "starjason"
        GITLAB_PASSWORD: ${{ secrets.JIHULAB }} // Generate here: https://gitlab.com/profile/personal_access_tokens
        GITLAB_PROJECT_ID: "25786" // https://gitlab.com/<namespace>/<repository>/edit
        GITHUB_TOKEN: ${{ secrets.PAT }} // https://docs.github.com/en/actions/reference/authentication-in-a-workflow#about-the-github_token-secret
