name: repo_sync_gitlab

on: 
  workflow_dispatch:
  #push:
  #  branches: [ main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: sync-gitlab
      run: |
         pwd
         ls -l 
         GITHUB_REPO="https://github.com/hbstarjason2021/jd-scripts-docker.git"
         GITLAB_TOKEN="${{ secrets.JIHULAB }}"
         GITLAB_REPO=https://oauth2:${GITLAB_TOKEN}@jihulab.com/hbstarjason/jd-scripts-docker.git
         
         git clone --mirror "$GITHUB_REPO" && cd `basename "$GITHUB_REPO"`
         git remote set-url --push origin "$GITLAB_REPO"
         git fetch -p origin
         git for-each-ref --format 'delete %(refname)' refs/pull | git update-ref --stdin
         git push --mirror
         
         echo "****** sync to gitlab success ******"
         
    #- name: Checkout repo
    #  uses: actions/checkout@v2
    #- name: Push gitlab
    #  run: |
    #     pwd
    #     ls -l 
    
    #- uses: wangchucheng/git-repo-sync@v0.1.0
    #  with:
    #    target-url: https://jihulab.com/hbstarjason/jd-scripts-docker.git
    #    target-username: starjason
    #    target-token: ${{ secrets.JIHULAB }}
    #- name: Mirror + trigger CI
    #  uses: SvanBoxel/gitlab-mirror-and-ci-action@master
    #  with:
    #    args: "https://jihulab.com/hbstarjason/jd-scripts-docker"
    #  env:
    #    GITLAB_HOSTNAME: "jihulab.com"
    #    GITLAB_USERNAME: "starjason"
    #    GITLAB_PASSWORD: ${{ secrets.JIHULAB }}
    #    GITLAB_PROJECT_ID: "25786"
    #    GITHUB_TOKEN: ${{ secrets.PAT }} 
